-- generated by `theme` -- do not edit by hand
return {
    active_border   = { colors = { "rgba(e0e0e0ee)",
                                    "rgba(1a1a1aee)" }, angle = 45 },
    inactive_border = "rgba(1a1a1aaa)",
    shadow_color    = "rgba(00000099)",
    rounding        = 0,
    rounding_power  = 3,
}
