-- LOOK AND FEEL ---------------------------------------------------------
-- Palette: mecha-no-onna (warm parchment on near-black).
-- Source: github.com/HANCORE-linux/omarchy-mechanoonna-theme
-- bg #1c1b19  fg #f0e4c5  accent #d4bd99
-- The matching hex values live in waybar/style.css, rofi/mecha.rasi,
-- kitty.conf and dunstrc.
local C = require("colors")   -- generated by `theme`

hl.config({
    general = {
        gaps_in  = 8,
        gaps_out = 16,

        border_size = 3,

        col = {
            active_border   = C.active_border,
            inactive_border = C.inactive_border,
        },

        resize_on_border = true,   -- grab borders with the mouse to resize
        allow_tearing    = false,
        layout           = "dwindle",
    },

    decoration = {
        -- 0 for `terminal` (square), 12 for `brown`: set by the family's
        -- `radius` in ~/.local/bin/theme and written to colors.lua.
        rounding       = C.rounding,
        rounding_power = C.rounding_power,

        active_opacity   = 1.0,
        inactive_opacity = 0.96,

        shadow = {
            enabled      = true,
            range        = 18,
            render_power = 3,
            color        = C.shadow_color,
        },

        blur = {
            enabled  = true,
            size       = 4,
            passes     = 2,
            contrast   = 1.05,
            brightness = 0.85,
            vibrancy   = 0.20,
        },
    },

    animations = { enabled = true },

    dwindle = { preserve_split = true },
    master  = { new_status = "master" },

    misc = {
        force_default_wallpaper = 0,     -- no anime mascot; hyprpaper handles it
        disable_hyprland_logo   = true,
    },

    -- XWayland apps (anything not native Wayland) render at 1x and get
    -- scaled by the compositor, so they stay sharp instead of blurry.
    xwayland = { force_zero_scaling = true },
})

-- Curves and animations (Hyprland defaults, kept as-is)
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1} } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1} } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}    } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1} } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}  } })
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" })
